version: '3'
services:
  postgres:
    image: postgres:13.1-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
    - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local